### ISSUE TITLE
🚀 Super Feature | Chat with AI on any Blog post.

### ISSUE THREAD

**Issue by aadeshkulkarni** [aadeshkulkarni/figuringout#135]
User visits a blog
User reads it
User wants to dig deeper into the nuances of the blog.

What will the user do ? Will they google it ? Will they chatgpt it ? Will they Youtube it ? Offcourse not!

They will interact with our Chat Module.

<img width="737" alt="Screenshot 2024-06-04 at 1 54 40 AM" src="https://github.com/aadeshkulkarni/medium-app/assets/67855887/b13ccef4-dcd1-4ed2-ac68-b94e370b9aa8">

### What ?
At the bottom of the blog page, the above chat box should be available. User can type a query related to the blog, and the app will use Generative AI to respond back with an answer. The entire chat will be appended below the blog so user can scroll up & down the history.

### Reference app:
https://pi.ai/discover

This is a super-feature. It needs backend & frontend development. Only a Ninja can do this. Be sure before taking it up. And if you take it up, share updates every 24 hours. If no response in 24 hours, you will be un-assigned from the issue so that someone else can try it out.

**Comment by Kunall-singh** [comment]
@aadeshkulkarni This will be a good challenge for me. I've already implemented a chat module using the OpenAI API before, but implementing a query system related to blog posts will be a new challenge. I would love to take on this challenge if it's still available.

**Comment by aadeshkulkarni** [comment]
Okay, please share your approach first.

**Comment by Kunall-singh** [comment]
In the backend, a new route will be created in blog.ts to connect to the OpenAI API using the OPENAI_API_KEY, with a prompt like "Given this blog content: "${blogContent}", answer the following question: ${userQuery}", where blogContent will be fetched from the blog. In the frontend, a new component ChatModule.tsx will be created to use Axios for fetching the API and passing the necessary data.

**Comment by Kunall-singh** [comment]
@aadeshkulkarni The frontend and backend implementation of the working chat module is complete. I need your suggestions on the following points:

Prompt Modification for Related Questions: As mentioned, the prompt needs to be modified after the first query. If the second question is related to the blog or is a continuous question based on the previous question and response, we can store the chat in local storage for now. We can then include the previous question and response to generate the next response. But if we don't want this, I guess the prompt i introduced before should be compatible with most questions that are not continuous but related to the blog.

Max Token Limit: We can set a maximum token limit at the backend. Users will not be able to exceed this limit, and we can show a warning in advance.

Local Storage vs. Database: I think local storage is a good option. Implementing a database would require additional logic to manage and recover chat histories, similar to ChatGPT. Since users reading a blog are likely to ask questions immediately, storing chats locally should suffice. If needed, users can ask further questions later. Thus, local storage with a limit seems like a practical solution.

Please share your thoughts.

**Comment by Kunall-singh** [comment]
@aadeshkulkarni need your suggestions on the design. 
![Screenshot 2024-06-13 111225](https://github.com/aadeshkulkarni/medium-app/assets/107796595/94d3e17a-cb43-4974-b770-7327fed52ffb)
![Screenshot 2024-06-13 111326](https://github.com/aadeshkulkarni/medium-app/assets/107796595/decbd256-e69f-484b-aef3-665043ff0b75)
or anything else?

**Comment by aadeshkulkarni** [comment]
Overall, both look nice.

The first design looks better, in my opinion. But it still needs to be duo-chromatic at max.  
The gray on Assistant response looks too dark, gives a feeling that its disabled. We can tone it down. Or keep it white.
Tone down the green with a lighter variation as well.
Can we use an icon instead of the label for `Reset Chat` ? That will eliminate the red color as well.

**Comment by aadeshkulkarni** [comment]
Thanks for your contribution. This was a big one. Keep up the good work. 🚀
